name: Create PDF Handout

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: tlmgr install german
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/Handout.pdf Readme.md
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output